# checkout

Tentei colocar as conexões dentro dos try catch, porém da maneira como implementei meu metodo de conexão isso não foi possivel,
o intellij acusava erro quando colocava a conexão dentro do try(){
